services:
  app:
    build:
      context: ./hygieneresto-backend/backend
      dockerfile: Dockerfile
    ports:
      - "${PORT}:${PORT}" # Utilisez la variable PORT définie ci-dessous
    environment:
      NODE_ENV: ${NODE_ENV:-development}
      PORT: 5001 # Port modifié à 5001
      HOST: ${HOST:-localhost}
      USERNAME: ${USERNAME:-rootttest}
      PASSWORD: ${PASSWORD:-root1234}
      DATABASE: ${DATABASE:-hygieneresto_db}
      DB_PORT: ${DB_PORT:-3306}
    depends_on:
      - db
    restart: always
    networks:
      - app-network

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${PASSWORD:-root1234}
      MYSQL_DATABASE: ${DATABASE:-hygieneresto_db}
      MYSQL_USER: ${USERNAME:-rootttest}
      MYSQL_PASSWORD: ${PASSWORD:-root1234}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network

volumes:
  db-data:

networks:
  app-network:
    driver: bridge
