version: '3.8'

services:
  app:
    build:
      context: ./hygieneresto-backend/backend  # La racine du projet est le contexte
      dockerfile: Dockerfile # Chemin vers le Dockerfile
    ports:
      - "${PORT}:${PORT}"
    environment:
      NODE_ENV: ${NODE_ENV:-development}
      PORT: ${PORT:-5000}
      HOST: ${HOST:-localhost}
      USERNAME: ${USERNAME:-rootttest}
      PASSWORD: ${PASSWORD:-root1234}
      DATABASE: ${DATABASE:-hygieneresto_db}
      DB_PORT: ${DB_PORT:-8889}
    depends_on:
      - db
    restart: always
    volumes:
      - ./backend:/usr/src/app # Monte le dossier backend dans le conteneur
    networks:
      - app-network

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${PASSWORD:-root1234}
      MYSQL_DATABASE: ${DATABASE:-hygieneresto_db}
      MYSQL_USER: ${USERNAME:-rootttest}
      MYSQL_PASSWORD: ${PASSWORD:-root1234}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network

volumes:
  db-data:

networks:
  app-network:
    driver: bridge
